import numpy as np

# Camera position in Head coordinate system
CAMERA_TOP = np.array([0.05871, 0.0, 0.06364])
CAMERA_BOTTOM = np.array([0.05071, 0.0, 0.01774])

# Field of view in radians
CAMERA_HFOV = 1.0629055144645467
CAMERA_VFOV = 0.8307767239493009
CAMERA_DFOV = 1.2671090369478832

# Pixel size in meters
CAMERA_PIXEL_SIZE = [1.9e-6, 1.9e-6]

# Focus range in meters
CAMERA_FOCUS_RANGE = [0.3, np.inf]

# Camera supported parameters
# Software parameters
CAMERA_KEEP_ALIVE_MIN = 0
CAMERA_KEEP_ALIVE_MAX = 1
CAMERA_KEEP_ALIVE_DEFULT = 0
# Hardware parameters
# Brightness
CAMERA_BRIGHTNESS_MIN = 0
CAMERA_BRIGHTNESS_MAX = 255
CAMERA_BRIGHTNESS_DEFAULT = 55
# Contrast
CAMERA_CONTRAST_MIN = 16
CAMERA_CONTRAST_MAX = 64
CAMERA_CONTRAST_DEFAULT = 32
# Saturation
CAMERA_SATURATION_MIN = 0
CAMERA_SATURATION_MAX = 255
CAMERA_SATURATION_DEFAULT = 128
# Hue
CAMERA_HUE_MIN = -180
CAMERA_HUE_MAX = 180
CAMERA_HUE_DEFAULT = 0
# Gain
CAMERA_GAIN_MIN = 32
CAMERA_GAIN_MAX = 255
CAMERA_GAIN_DEFAULT = 32
# Horizontal flip
CAMERA_HORIZONTAL_FLIP_MIN = 0
CAMERA_HORIZONTAL_FLIP_MAX = 1
CAMERA_HORIZONTAL_FLIP_DEFAULT = 0
# Vertical flip
CAMERA_VERTICAL_FLIP_MIN = 0
CAMERA_VERTICAL_FLIP_MAX = 1
CAMERA_VERTICAL_FLIP_DEFAULT = 0
# Auto white balance
CAMERA_AUTO_WHITE_BALANCE_MIN = 0
CAMERA_AUTO_WHITE_BALANCE_MAX = 1
CAMERA_AUTO_WHITE_BALANCE_DEFAULT = 1
# Frames Per Second
CAMERA_FPS_MIN = 1
CAMERA_FPS_MAX = 30
CAMERA_FPS_DEFAULT = 5
